[workspace]
members = ["env-reader","fibonacci", "fs-reader",
    "hello-world", "infinite-loop", "long-output-guest", "memory-hog", "net-guest", "panic-guest", "stdout-spammer",
]
resolver = "2"

# Optimization: Production Wasm should be small
[profile.release]
opt-level = "s"      # Optimize for binary size
strip = true         # Remove symbols
lto = true           # Link Time Optimization
